routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/teacher', 'TeacherController@lesson');
Route::get('/student', function () {
    return view('student');
});


#///# Static Pages
Route::get('/about', function () {
    return view('static.about');
});
Route::get('/contact', function () {
    return view('static.contact');
});
Route::get('/faq', function () {
    return view('static.faq');
});
Route::get('/terms', function () {
    return view('static.terms');
});


Route::post('/ajaxlogin', 'UserController@login');

#///# Administrator routes
Route::group(['prefix' => 'admin', 'middleware' => 'role:admin'], function () {
    Route::get('/', 'AdminController@index');
    Route::resource('/user', 'UserController');
    Route::resource('/course', 'CourseController');
    Route::resource('/lesson', 'LessonController');
});


Route::group(['middleware' => 'auth'], function () {
    #///# User routes
    Route::get('/dashboard', 'UserController@userDashboard');
    Route::get('/schedule', 'UserController@userLessons');
    Route::get('/payment', 'UserController@payment');
    #///# Calendar Routes
    Route::get('/calendar', 'CalendarController@index');
    Route::post('/calendar/nextTwoDays', 'CalendarController@nextTwoDaysData');
    Route::post('/calendar/store', 'CalendarController@saveUserLessons');


    #///# teacher routes
    Route::group(['prefix' => 'teacher', 'middleware' => 'role:teacher'], function () {
        Route::get('/', 'TeacherController@index');
        Route::get('/start/{id}', 'TeacherController@startLesson');
    });


    #///# twilio video rooms
    Route::get('/lessons', "TwilioController@showRooms");
    Route::prefix('lesson')->group(function () {
        Route::post('join', 'TwilioController@joinRoom');
        Route::post('create', 'TwilioController@createRoom');
        Route::post('check', 'TwilioController@checkRoom');

        Route::get('join/{id}', 'UserController@joinLesson');
    });

    #///#other
    Route::post('/lesson/status/update', 'LessonController@changeStatus');
});

app/Lesson.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Lesson extends Model
{
    public $timestamps = false;
    protected $fillable = [
        'name', 'teacher_id', 'course_id', 'start_date', 'lesson', 'status'
    ];

    protected $dates = [
        'start_date'
    ];

    public function course()
    {
        return $this->belongsTo('App\Course');
    }

    public function teacher()
    {
        return $this->belongsTo('App\User', 'teacher_id');
    }

    public function user(){
        return $this->belongsToMany('App\User');
    }
}

app/Http/Controllers/LessonController.php
<?php

namespace App\Http\Controllers;

use App\Lesson;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;

class LessonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    public function getLessonsByDate(Request $request, $from, $to, $lesson = 1)
    {
        if ($request->ajax()) {

            $lessons = Lesson::all();
            if ($lessons) {
                return response()->json(['lessons' => $lessons]);
            } else {
                return response()->json(['error' => 'failed delete'], 500);
            }

        }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $lessonNames = [
            '0',
            '1 გაკვეთილი',
            '2 გაკვეთილი',
            '3 გაკვეთილი',
            '4 გაკვეთილი',
            '5 გაკვეთილი',
            '6 გაკვეთილი',
            '7 გაკვეთილი',
            '8 გაკვეთილი',
            '9 გაკვეთილი',
            '10 გაკვეთილი'
        ];
        $holidays = [
            '01/01',
            '01/02',
            '01/14',
            '01/19',
            '03/03',
            '03/08',
            '04/09',
            '05/09',
            '05/12',
            '05/26',
            '08/28',
            '10/14',
            '11/23',
            '12/31'
        ];
        $dt = Carbon::createFromFormat('d/m/y', $request['start_date']);
        $dates[] = $request['start_date'];
        for ($i = 0; $i < 9; $i++) {
            $dt->addDays(2);
            /*while (true) {
                if (in_array($dt->format('m/d'), $holidays) || $dt->isWeekend()) {
                    // the day is either in the holidays array or is a weekend
                    // add one day
                    $dt->addDay();
                } else {
                    break;
                }
            }*/
            $dates[] = $dt->format('d/m/y');
        }
        $teachers = User::where('type', 2)->get();
        return view('admin.lesson.create',
            ['teachers' => $teachers,
                'dates' => $dates,
                'lessonNames' => $lessonNames,
                'request' => $request->all()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = [];
        foreach ($request['name'] as $k => $value) {
            $data[] = ['name' => $value,
                'teacher_id' => $request['teacher_id'][$k],
                'course_id' => $request['course_id'],
                'lesson' => $k + 1,
                'start_date' => Carbon::createFromFormat('d/m/y G:i', $request['start_date'][$k] . ' ' . $request['start_hour'][$k])
            ];
        }
        //dd($data);
        $lessons = Lesson::insert($data);

        if ($lessons) {
            return redirect()->route('course.index');
        } else {
            return redirect()->back()->withInput();
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        foreach ($request['id'] as $k => $rid) {
            $lesson = Lesson::findOrFail($rid);

            $input = [
                'name' => $request['name'][$k],
                'teacher_id' => $request['teacher_id'][$k],
                'start_date' => Carbon::createFromFormat('d/m/y G:i', $request['start_date'][$k] . ' ' . $request['start_hour'][$k])
            ];

            $lesson->fill($input)->save();
        }

        $request->session()->flash('flash_message', 'კურსი წარმატებით განახლდა');

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function changeStatus(Request $request){
        if ($request->isMethod('post')) {
            $lesson = Lesson::findOrFail($request->id);
            $lesson->status = $request->status;
            if($lesson->save()){
                return response()->json([
                    'success' => 'true'
                ]);
            }
            return response()->json([
                'success' => 'false'
            ], 500);

        }
    }
}

resources/views/admin/lesson/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="col-md-8 col-md-offset-2">
        <h3>გაკვეთილების შექმნა</h3>
        <form class="form-horizontal" role="form" method="POST" action="{{ route('lesson.store') }}">
            {{ csrf_field() }}

            <input type="hidden" name="course_id" value="{{$request['course_id']}}">
            @for($g = 1; $g < 11; $g++)
                <div class="row">
                    <div class="col-md-8">
                        <div class="{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="form-label">{{$g}} გაკვეთილის სახელი</label>
                            <input id="name" type="text" class="form-control" name="name[]"
                                   value="{{ old('name') ? old('name') : $lessonNames[$g] }}" required>

                            @if ($errors->has('name'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-4 ">
                        <div class="{{ $errors->has('teacher_id') ? ' has-error' : '' }}">
                            <label>მასწავლებელი</label>
                            <select name="teacher_id[]" class="form-control">
                                @foreach($teachers as $teacher)
                                    <option value="{{$teacher->id}}"
                                            {{ $request['teacher_id'] == $teacher->id ? 'selected' : '' }}
                                    >{{$teacher->name}}</option>
                                @endforeach
                            </select>
                            @if ($errors->has('teacher_id'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                            @endif
                        </div>
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-8">
                        <div class="{{ $errors->has('start_date') ? ' has-error' : '' }}">

                            <label for="date">დაწყების დრო</label>

                            <div class="input-group date datepicker ">
                                <input type="text" id="date" value="{{$dates[$g - 1]}}" name="start_date[]"
                                       class=" form-control"><span
                                        class="input-group-addon"><i
                                            class="glyphicon glyphicon-th"></i></span>
                            </div>
                            @if ($errors->has('start_date'))
                                <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="{{ $errors->has('start_hour') ? ' has-error' : '' }}">
                            <label>საათი</label>
                            <select name="start_hour[]" class="form-control">
                                @for($i = 1; $i <= 24; $i++)
                                    @php
                                        $date = new \Carbon\Carbon("$i:00");
                                    @endphp
                                    <option value="{{$date->format('H:i')}}"
                                            {{ $request['start_hour'] == $date->format('H:i') ? 'selected' : '' }}
                                    >{{$date->format('H:i')}}</option>
                                @endfor
                            </select>
                        </div>
                    </div>
                </div>
                <hr/>

            @endfor

            <div class="form-row">
                <button class="btn btn-success pull-right" type="submit">შენახვა</button>
            </div>
            <br/>
        </form>
    </div>

@endsection

@section('scripts')
@endsection