routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/teacher', 'TeacherController@lesson');
Route::get('/student', function () {
    return view('student');
});


#///# Static Pages
Route::get('/about', function () {
    return view('static.about');
});
Route::get('/contact', function () {
    return view('static.contact');
});
Route::get('/faq', function () {
    return view('static.faq');
});
Route::get('/terms', function () {
    return view('static.terms');
});


Route::post('/ajaxlogin', 'UserController@login');

#///# Administrator routes
Route::group(['prefix' => 'admin', 'middleware' => 'role:admin'], function () {
    Route::get('/', 'AdminController@index');
    Route::resource('/user', 'UserController');
    Route::resource('/course', 'CourseController');
    Route::resource('/lesson', 'LessonController');
});


Route::group(['middleware' => 'auth'], function () {
    #///# User routes
    Route::get('/dashboard', 'UserController@userDashboard');
    Route::get('/schedule', 'UserController@userLessons');
    Route::get('/payment', 'UserController@payment');
    #///# Calendar Routes
    Route::get('/calendar', 'CalendarController@index');
    Route::post('/calendar/nextTwoDays', 'CalendarController@nextTwoDaysData');
    Route::post('/calendar/store', 'CalendarController@saveUserLessons');


    #///# teacher routes
    Route::group(['prefix' => 'teacher', 'middleware' => 'role:teacher'], function () {
        Route::get('/', 'TeacherController@index');
        Route::get('/start/{id}', 'TeacherController@startLesson');
    });


    #///# twilio video rooms
    Route::get('/lessons', "TwilioController@showRooms");
    Route::prefix('lesson')->group(function () {
        Route::post('join', 'TwilioController@joinRoom');
        Route::post('create', 'TwilioController@createRoom');
        Route::post('check', 'TwilioController@checkRoom');

        Route::get('join/{id}', 'UserController@joinLesson');
    });

    #///#other
    Route::post('/lesson/status/update', 'LessonController@changeStatus');
});

app/Course.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Course extends Model
{
    public $timestamps = false;

    protected $fillable = [
        'name', 'teacher_id', 'start_date'
    ];

    public function lessons()
    {
        return $this->hasMany('App\Lesson');
    }
}

app/Http/Controllers/CourseController.php
<?php

namespace App\Http\Controllers;

use App\Course;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;

class CourseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $courses = Course::paginate(15);
        return view('admin.course.courses', ['courses' => $courses]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $teachers = User::where('type', 2)->get();
        return view('admin.course.create', ['teachers' => $teachers]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $date = Carbon::createFromFormat('d/m/y G:i', $request['start_date'] . ' ' . $request['start_hour']);

        $course = Course::create([
            "name" => $request['name'],
            "teacher_id" => $request['teacher_id'],
            "start_date" => $date
        ]);

        if ($course) {
            return redirect()->route('lesson.create',
                [
                    'teacher_id' => $request['teacher_id'],
                    'start_date' => $request['start_date'],
                    'start_hour' => $request['start_hour'],
                    'course_id' => $course->id
                ]);
        } else {
            return redirect()->back()->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $course = Course::find($id);
        $teachers = User::where('type', 2)->get();

        return view('admin.course.edit', ['course' => $course, 'teachers' => $teachers]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $course = Course::findOrFail($id);

        $input = $request->all();

        $course->fill($input)->save();

        $request->session()->flash('flash_message', 'კურსი წარმატებით განახლდა');

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        if ($request->ajax()) {

            $course = Course::findOrFail($id);

            if ($course->delete()) {
                return response()->json(['message' => 'sucessfully deleted']);
            } else {
                return response()->json(['error' => 'failed delete'], 500);
            }

        }
    }
}

resources/views/admin/course/courses.blade.php
@extends('layouts.admin')

@section('content')
    <div class="col-md-8 col-md-offset-2">
        <a class="btn btn-success" href="{{route('course.create')}}">Create Course</a>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>ID</th>
                <th>დასახელება</th>
                <th><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></th>
                <th><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></th>
            </tr>
            </thead>
            <tbody>
            @foreach ($courses as $course)
                <tr>
                    <td>{{ $course->id }}</td>
                    <td>{{ $course->name }}</td>
                    <td><a type="button" href="{{route('course.edit', $course->id)}}"
                           class="btn btn-info btn-xs">
                            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                        </a></td>
                    <td>
                        <button type="button" class="btn btn-danger btn-xs deleteRow"
                                data-url="{{route('course.destroy', $course->id)}}"
                        ><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

        <div class="text-center">
            {{ $courses->links() }}
        </div>
    </div>
@endsection

@section('scripts')
@endsection

resources/views/admin/course/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="col-md-8 col-md-offset-2">
        <form class="form-horizontal" role="form" method="POST" action="{{ route('course.store') }}">
            {{ csrf_field() }}
            <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
                <label for="name" class="form-label">საელი</label>
                <input id="name" type="text" class="form-control" name="name"
                       value="{{ old('name') }}" required autofocus>

                @if ($errors->has('name'))
                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                @endif
            </div>
            <div class="form-group {{ $errors->has('teacher_id') ? ' has-error' : '' }}">
                <label>მთავარი მასწავლებელი</label>
                <select name="teacher_id" class="form-control">
                    @foreach($teachers as $teacher)
                        <option value="{{$teacher->id}}">{{$teacher->name}}</option>
                    @endforeach
                </select>
                @if ($errors->has('teacher_id'))
                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                @endif
            </div>
            <div class="form-group {{ $errors->has('start_date') ? ' has-error' : '' }}">

                <label for="date">დაწყების დრო</label>
                <div class="row">
                    <div class="col-md-8">
                        <div class="input-group date datepicker ">

                            <input type="text" id="date" name="start_date" class=" form-control"><span
                                    class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <select name="start_hour" class="form-control">
                            @for($i = 1; $i <= 24; $i++)
                                @php
                                    $date = new \Carbon\Carbon("$i:00");
                                @endphp
                                <option value="{{$date->format('H:i')}}">{{$date->format('H:i')}}</option>
                            @endfor
                        </select>
                    </div>
                    @if ($errors->has('start_date'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group">
                <button class="btn btn-success pull-right" type="submit">შენახვა</button>
            </div>
        </form>
    </div>

@endsection

@section('scripts')
@endsection

resources/views/admin/course/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="col-md-8 col-md-offset-2">
        <form class="form-horizontal" role="form" method="POST" action="{{ route('course.update', $course->id) }}">
            {{ csrf_field() }}
            {{ method_field('put') }}
            <div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
                <label for="name" class="form-label">საელი</label>
                <input id="name" type="text" class="form-control" name="name"
                       value="{{ old('name', $course->name) }}" required autofocus>

                @if ($errors->has('name'))
                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                @endif
            </div>
            <div class="form-group {{ $errors->has('teacher_id') ? ' has-error' : '' }}">
                <label>მთავარი მასწავლებელი</label>
                <select name="teacher_id" class="form-control">
                    @foreach($teachers as $teacher)
                        <option value="{{$teacher->id}}"
                                {{ old('teacher_id', $course->teacher_id) == $teacher->id ? 'selected' : '' }}
                        >{{$teacher->name}}</option>
                    @endforeach
                </select>
                @if ($errors->has('teacher_id'))
                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                @endif
            </div>
            <div class="form-group {{ $errors->has('start_date') ? ' has-error' : '' }}">
                @php
                    $carbon = new \Carbon\Carbon($course->start_date);
                    $dbdate = $carbon->format('d/m/y');
                    $hour = $carbon->format('H:i');
                @endphp
                <label for="date">დაწყების დრო</label>
                <div class="row">
                    <div class="col-md-8">
                        <div class="input-group date datepicker ">

                            <input type="text" id="date" name="start_date" class=" form-control"
                                   value="{{$dbdate}}"><span
                                    class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <select name="start_hour" class="form-control">
                            @for($i = 1; $i <= 24; $i++)
                                @php
                                    $date = new \Carbon\Carbon("18:00");
                                @endphp
                                <option value="{{$date->format('H:i')}}">{{$date->format('H:i')}}</option>
                            @endfor
                        </select>
                    </div>
                    @if ($errors->has('start_date'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group">
                <button class="btn btn-success pull-right" type="submit">კურსის შენახვა</button>
            </div>
        </form>
    </div>
<div class="clearfix"></div>
    <h3>გაკვეთილების სია</h3>
    <form class="form-horizontal" role="form" method="POST" action="{{ route('lesson.update', 0) }}">
        {{ csrf_field() }}
        {{ method_field('put') }}
        @foreach($course->lessons as $k => $lesson)
            <div class="row">
                <div class="col-md-8">
                    <div class="{{ $errors->has('name') ? ' has-error' : '' }}">
                        <label for="name" class="form-label">{{$k+1}} გაკვეთილის სახელი</label>
                        <input type="hidden" name="id[]" value="{{$lesson->id}}">
                        <input id="name" type="text" class="form-control" name="name[]"
                               value="{{ old('name', $lesson->name) }}" required autofocus>

                        @if ($errors->has('name'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                        @endif
                    </div>
                </div>
                <div class="col-md-4 ">
                    <div class="{{ $errors->has('teacher_id') ? ' has-error' : '' }}">
                        <label>მასწავლებელი</label>
                        <select name="teacher_id[]" class="form-control">
                            @foreach($teachers as $teacher)
                                <option value="{{$teacher->id}}"
                                        {{ $lesson->teacher_id == $teacher->id ? 'selected' : '' }}
                                >{{$teacher->name}}</option>
                            @endforeach
                        </select>
                        @if ($errors->has('teacher_id'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                        @endif
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-md-8">
                    <div class="{{ $errors->has('start_date') ? ' has-error' : '' }}">
                        @php
                            $carbon = new \Carbon\Carbon($lesson->start_date);
                            $dbdate = $carbon->format('d/m/y');
                            $hour = $carbon->format('H:i');
                        @endphp
                        <label for="date">დაწყების დრო</label>

                        <div class="input-group date datepicker ">
                            <input type="text" id="date" value="{{$dbdate}}" name="start_date[]"
                                   class=" form-control"><span
                                    class="input-group-addon"><i
                                        class="glyphicon glyphicon-th"></i></span>
                        </div>
                        @if ($errors->has('start_date'))
                            <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                        @endif
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="{{ $errors->has('start_hour') ? ' has-error' : '' }}">
                        <label>საათი</label>
                        <select name="start_hour[]" class="form-control">
                            @for($i = 1; $i <= 24; $i++)
                                @php
                                    $date = new \Carbon\Carbon("$i:00");
                                @endphp
                                <option value="{{$date->format('H:i')}}"
                                        {{ $hour == $date->format('H:i') ? 'selected' : '' }}
                                >{{$date->format('H:i')}}</option>
                            @endfor
                        </select>
                    </div>
                </div>
            </div>
            <hr/>

        @endforeach

        <div class="form-row">
            <button class="btn btn-success pull-right" type="submit">გაკვეთილების შენახვა</button>
        </div>
        <br/>
    </form>
    </div>


@endsection

@section('scripts')
@endsection